name: build ami

on:
  workflow_run:
    workflows: ["deploy rds"]
    type:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_DEFAULT_OUTPUT: json

    steps:

      - uses: actions/checkout@v4

      - name: Initialize packer
        working-directory: packer 
        run: |
          packer version



           
             
          



  
  